### ISSUE TITLE
Step precision

### ISSUE THREAD

**Issue by filipSu** [RadMie/ng-knob#6]
Hello,

firstly, ng-knob is very nice component. Works great. My question is, are you considering to make "step" other type then integer?Unfortunately, I need to use step 0.5.

Thank you

**Comment by filipSu** [comment]
Such a quick fix. Great job. Thank you

**Comment by filipSu** [comment]
I tried to use step 0.5 and got an error. Knob wasn't displayed at all.

`TypeError: this.value.toFixed is not a function
    at Knob.drawArcs (http://192.168.0.24:9000/bower_components/ng-knob/dist/ng-knob.js:93:41)
    at Knob.draw (http://192.168.0.24:9000/bower_components/ng-knob/dist/ng-knob.js:201:14)
    at drawKnob (http://192.168.0.24:9000/bower_components/ng-knob/dist/ng-knob.js:354:26)
    at link (http://192.168.0.24:9000/bower_components/ng-knob/dist/ng-knob.js:360:17)
    at http://192.168.0.24:9000/bower_components/angular/angular.js:9033:44
    at invokeLinkFn (http://192.168.0.24:9000/bower_components/angular/angular.js:9039:9)
    at nodeLinkFn (http://192.168.0.24:9000/bower_components/angular/angular.js:8533:11)
    at compositeLinkFn (http://192.168.0.24:9000/bower_components/angular/angular.js:7929:13)
    at nodeLinkFn (http://192.168.0.24:9000/bower_components/angular/angular.js:8528:24)
    at compositeLinkFn (http://192.168.0.24:9000/bower_components/angular/angular.js:7929:13) <ui-knob value="value" options="options" class="ng-isolate-scope">`

These are my knob settings:
`$scope.options = {
      startAngle: 30,
      endAngle: 330,
      min: parseInt($scope.item.min),
      max: parseInt($scope.item.max),
      step: 0.5,
      unit: $scope.item.unit,
      readonly: false,
      scale: {
        enabled: true,
        type: 'dots',
        color: 'rgba(0,0,0,.1)',
        width: 2,
        quantity: parseInt((($scope.item.max-$scope.item.min)/2)),
        spaceWidth: 10
      },
      trackWidth: 15,
      barWidth: 25,
      trackColor: 'rgba(0,0,0,.1)',
      barColor: '#FF4081',
      prevBarColor: '#727272',
      textColor: '#727272',
      animate: {
        enabled : false
      },
      displayPrevious: true
    };`

**Comment by RadMie** [comment]
What browser do you use?

**Comment by filipSu** [comment]
Chrome 48.0.2564 on Fedora 64bit

**Comment by RadMie** [comment]
Maybe you write string to $scope.value

**Comment by filipSu** [comment]
Yes, you were right. Everything works now. Thank you
